version: 1.0.0-{build}
image: Visual Studio 2017
configuration: Release
platform: x64
build_script:
  - cmd: >-
      "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

      cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - NMake Makefiles" .

      cmake --build .
test_script:
  - cmd: >-
      bin\SpeckleUnitTests.exe

      bin\SpeckleIntegrationTests.exe